datasets:
  report:
    path: CSVPATH #svbenchmark.sv.summary.csv
    separator: ","
views:
  test:
    dataset: report
    render-table:
      columns:
        Tool:
          display-mode: normal
        Type:
          display-mode: normal
        Filter:
          display-mode: normal
        TP_base:
          display-mode: normal
        TP:
          display-mode: normal
        FN:
          display-mode: normal
        TP_call:
          display-mode: normal
        FP:
          display-mode: normal
        UNK:
          display-mode: normal
# FP_gt,FP_al,Recall,Precision,Frac_NA,F1,TRUTH_TiTv_ratio,QUERY_TiTv_ratio,TRUTH_het_hom_ratio,QUERY_het_hom_ratio
